version: '3'
services:

  dsw_server:
    #image: datastewardshipwizard/wizard-server:2.14.0
    image: docker.ds-wizard.org/wizard-server:feature-DSW-1055
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - ./server/application.yml:/application/engine-wizard/config/application.yml:ro
      - ./server/integration.yml:/application/engine-wizard/config/integration.yml:ro

  dsw_client:
    #image: datastewardshipwizard/wizard-client:2.14.0
    image: docker.ds-wizard.org/wizard-client:feature-DSW-1076
    restart: always
    ports:
      - 8080:80
    environment:
      API_URL: http://localhost:3000

  docworker:
    #image: datastewardshipwizard/document-worker:2.14.0
    #image: docworker:local
    image: docker.ds-wizard.org/document-worker:feature-DSW-1077
    restart: always
    depends_on:
      - postgres
      - minio
    volumes:
      - ./docworker/config.yml:/app/config.yml:ro

  postgres:
    image: postgres:13.2
    restart: always
    # (!) Expose only for debugging locally or set-up authentication
    ports:
      - 127.0.0.1:15432:5432
    environment:
      POSTGRES_DB: engine-wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # (!) Mount for persistent data
    # volumes:
    #  - db-data:/data/db
    # OR
    #  - ./db-data:/data/db

  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    command: server /data
    # (!) Expose only for debugging locally or set-up authentication
    ports:
     - 127.0.0.1:19000:9000
    # (!) Mount and backup for persistent data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    # (!) Mount for persistent data
    # volumes:
    #  - s3-data:/data
    # OR
    #  - ./s3-data:/data

# volumes:
#   db-data:
#   s3-data:
